packageExtensions:
  '@atls/typeorm-logger@*':
    dependencies:
      typeorm: '*'
  '@atls/nestjs-grpc-reflection@*':
    dependencies:
      long: '*'
  '@ilink-ui-parts/link@*':
    dependencies:
      '@emotion/css': '*'
  '@ilink-ui-parts/layout@*':
    dependencies:
      csstype: '*'
  '@grpc/grpc-js@*':
    dependencies:
      '@types/long': '*'
  next@*:
    dependencies:
      '@types/react-dom': '*'
  '@nestjs/common@*':
    dependencies:
      '@grpc/proto-loader': '*'
      cache-manager: '*'
      reflect-metadata: '*'
      rxjs: '*'
  '@nestjs/core@*':
    dependencies:
      '@nestjs/platform-express': '*'
      '@nestjs/websockets': '*'
      reflect-metadata: '*'
      rxjs: '*'
  '@nestjs/cqrs@*':
    dependencies:
      reflect-metadata: '*'
      rxjs: '*'
  '@nestjs/microservices@*':
    dependencies:
      '@grpc/grpc-js': '*'
      '@grpc/proto-loader': '*'
      '@nestjs/websockets': '*'
      mqtt: '*'
      reflect-metadata: '*'
      rxjs: '*'
      kafkajs: '*'
  '@nestjs/typeorm@*':
    dependencies:
      rxjs: '*'
  '@nestjs/websockets@*':
    dependencies:
      '@nestjs/platform-socket.io': '*'
  typeorm@*:
    dependencies:
      pg: '*'
      pg-query-stream: '*'
      sqlite3: '*'
  pg-cursor@*:
    dependencies:
      pg: '*'
  follow-redirects@*:
    dependencies:
      debug: '*'
  debug@*:
    dependencies:
      supports-color: '*'
  '@sumsub/websdk-react@*':
    dependencies:
      '@sumsub/websdk': '*'

yarnPath: .yarn/releases/yarn-0.0.1-git.20220423.hash-8db8883.cjs
