yarnPath: .yarn/releases/yarn-0.0.1-git.20220423.hash-8db8883.cjs

packageExtensions:
  '@apollo/client@*':
    dependencies:
      react: '17'
      react-dom: '17'
      graphql: '*'
  '@atls/typeorm-logger@*':
    dependencies:
      typeorm: '*'
  '@atls/nestjs-grpc-reflection@*':
    dependencies:
      long: '*'
  '@ilink-ui-parts/link@*':
    dependencies:
      '@emotion/css': '*'
  '@ilink-ui-parts/layout@*':
    dependencies:
      csstype: '*'
  '@grpc/grpc-js@*':
    dependencies:
      '@types/long': '*'
  next@*:
    dependencies:
      '@types/react-dom': '*'
  '@nestjs/common@*':
    dependencies:
      '@grpc/proto-loader': '*'
      cache-manager: '*'
      reflect-metadata: '*'
      rxjs: '*'
  '@nestjs/core@*':
    dependencies:
      '@nestjs/platform-express': '*'
      '@nestjs/websockets': '*'
      reflect-metadata: '*'
      rxjs: '*'
  '@nestjs/cqrs@*':
    dependencies:
      reflect-metadata: '*'
      rxjs: '*'
  '@nestjs/microservices@*':
    dependencies:
      '@grpc/grpc-js': '*'
      '@grpc/proto-loader': '*'
      '@nestjs/websockets': '*'
      mqtt: '*'
      reflect-metadata: '*'
      rxjs: '*'
      kafkajs: '*'
  '@nestjs/typeorm@*':
    dependencies:
      rxjs: '*'
  '@nestjs/websockets@*':
    dependencies:
      '@nestjs/platform-socket.io': '*'
  '@nestjs/apollo@*':
    dependencies:
      graphql: '*'
  '@nestjs/graphql@*':
    dependencies:
      class-validator: '*'
      class-transformer: '*'
  typeorm@*:
    dependencies:
      pg: '*'
      pg-query-stream: '*'
      sqlite3: '*'
  pg-cursor@*:
    dependencies:
      pg: '*'
  follow-redirects@*:
    dependencies:
      debug: '*'
  debug@*:
    dependencies:
      supports-color: '*'
  '@sumsub/websdk-react@*':
    dependencies:
      '@sumsub/websdk': '*'
  '@atls/nestjs-gateway@*':
    dependencies:
      ws: '*'
  '@atls/nestjs-grpc-http-proxy@*':
    dependencies:
      express: '*'
  '@graphql-mesh/store@*':
    dependencies:
      '@graphql-mesh/types': '*'
  '@graphql-mesh/types@*':
    dependencies:
      '@graphql-mesh/store': '*'
  '@graphql-tools/graphql-tag-pluck@*':
    dependencies:
      '@vue/compiler-sfc': '*'
      svelte2tsx: '*'
  '@graphql-typed-document-node/core@*':
    dependencies:
      graphql: '*'
  graphql-tag@*:
    dependencies:
      graphql: '*'
  pino@*:
    dependencies:
      pino-pretty: '*'
  svelte2tsx@*:
    dependencies:
      svelte: '*'
  ws@*:
    dependencies:
      bufferutil: '*'
      utf-8-validate: '*'
  node-fetch@*:
    dependencies:
      encoding: '*'
