version: '3.8'

services:
  yarn:
    image: node:16
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn

  db:
    image: bitnami/postgresql
    environment:
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=db
    ports:
      - 5432:5432

  gcs:
    image: fsouza/fake-gcs-server
    command: -scheme http -external-url http://gcs:4443
    volumes:
      - .data/gcs:/data
    ports:
      - 8600:4443

  kratos-migrate:
    depends_on:
      - db
    image: oryd/kratos:v0.8.2-alpha.1
    environment:
      - DSN=postgres://postgres:password@db:5432/db?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ./config/ory/kratos
        target: /config/kratos
    command: -c /config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure

  kratos:
    depends_on:
      - kratos-migrate
      - mailslurper
      - db
    image: oryd/kratos:v0.8.2-alpha.1
    ports:
      - '4433:4433'
      - '4434:4434'
    restart: unless-stopped
    environment:
      - DSN=postgres://postgres:password@db:5432/db?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    command: serve -c /config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./config/ory/kratos
        target: /config/kratos

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'

  identity:
    image: node:16
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn workspace @identity/accounts-app-entrypoint dev
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://localhost:4433/
      - KRATOS_ADMIN_URL=http://kratos:4434/
      - BASE_URL=http://localhost:3000
      - PRIVATE_GATEWAY_URL=http://localhost:3001/
    depends_on:
      - kratos
      - private-gateway
      - public-gateway
    networks:
      - default
    ports:
      - 3000:3000

  verification:
    image: node:16
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn workspace @verification/service-entrypoint dev
    networks:
      - default
    environment:
      - DB_HOST=db
      - SUMSUB_APP_TOKEN=sbx:NzowShNiQ5DZWdY0oS1hN8F3.c2bF9HxN5TJzVI8yyf7q2F0YsUBEeFnV
      - SUMSUB_SECRET_KEY=HATEOOllPBMAxjqG2CCJL5uy2eFFlbVj
    depends_on:
      - db

  files:
    image: node:16
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn workspace @files/service-entrypoint dev
    networks:
      - default
    environment:
      - DB_HOST=db
    env_file:
      - .env
    depends_on:
      - db

  private-gateway:
    image: node:16
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn workspace @gateway/private-gateway-entrypoint dev
    environment:
      - VERIFICATION_SERVICE_URL=verification:50051
    networks:
      - default
    ports:
      - 3001:3000
    depends_on:
      - verification

  public-gateway:
    image: node:16
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn workspace @gateway/public-gateway-entrypoint dev
    networks:
      - default
    environment:
      - FILES_SERVICE_URL=files:50051
    depends_on:
      - files
    ports:
      - 3002:3000
