export * from './add-address-document.command-handler'
export * from './add-id-document.command-handler'
export * from './create-applicant.command-handler'
export * from './update-address.command-handler'
export * from './update-applicant.commnd-handler'
export * from './verify-applicant.command-handler'
