// eslint-disable-next-line no-shadow
export enum Step {
  BASIC_INFORMATION = 'BASIC_INFORMATION',
  ADDRESS = 'ADDRESS',
  PROOF_OF_IDENTITY_1 = 'PROOF_OF_IDENTITY_1',
  PROOF_OF_IDENTITY_2 = 'PROOF_OF_IDENTITY_2',
  PROOF_OF_ADDRESS = 'PROOF_OF_ADDRESS',
  DATA_VERIFICATION = 'DATA_VERIFICATION',
}
